name: Build Releases
on:
  push:
    tags:
      - v*

jobs:
  build:
    name: Build
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - { target: x86_64-unknown-linux-musl, os: ubuntu-latest }
          - { target: x86_64-pc-windows-msvc,    os: windows-latest }
          - { target: x86_64-apple-darwin,       os: macos-latest }
          - { target: aarch64-apple-darwin,      os: macos-latest }

    steps:
      - uses: actions/checkout@v2

      - name: Install toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          target: ${{ matrix.target }}
          override: true

      - name: Build
        uses: actions-rs/cargo@v1
        with:
          use-cross: false
          command: build
          args: --release --target=${{ matrix.target }}

      - name: Zip (Windows)
        shell: bash
        if: runner.os == 'Windows'
        run: |
          mv target/${{ matrix.target }}/release/mcim.exe .
          powershell Compress-Archive mcim.exe mcim-${{ matrix.target }}.zip
      - name: Zip (Other)
        shell: bash
        if: runner.os != 'Windows'
        run: |
          mv target/${{ matrix.target }}/release/mcim .
          zip mcim-${{ matrix.target }}.zip mcim

      - name: Upload Github Assets
        uses: softprops/action-gh-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          files: mcim-${{ matrix.target }}.zip
          prerelease: ${{ contains(github.ref, '-') }}
